#!/usr/bin/env perl

use strict;
use warnings;
use 5.010;
use Data::Dumper;
use Device::SerialPort;
use Time::HiRes 'sleep';

our $VERSION = '0.0';

my $port = Device::SerialPort->new("/dev/ttyUSB0", 0);

$port->baudrate(19200);
$port->parity("none");
$port->databits(8);
$port->stopbits(1);
$port->handshake("none");

#
# USAGE
#
# perl ser 1 <card> <state>
#
# card: Karten-ID (master == 1, weitere nach Jumper (2, 3, ...))
# state: Relais-Status, binär. 0 = alle aus, 255 = alle an, etc.
#

my @bytes = @ARGV;
$bytes[3] = int($bytes[0]) ^ int($bytes[1]) ^ int($bytes[2]);
my $cnt = $port->write( join('',  map { chr($_) } @bytes ) );
printf("%08b " x @bytes . "%d\n", @bytes, $cnt);
sleep(5);
for (1 .. 4) {
	my ($cnt, $saw) = $port->read(1);
	printf(" :: %d %s ", $cnt, unpack('b*', $saw));
}
say "";


__END__

=head1 NAME

=head1 SYNOPSIS

=head1 VERSION

=head1 DESCRIPTION

=head1 OPTIONS

=over

=back

=head1 EXIT STATUS

=head1 CONFIGURATION

None.

=head1 DEPENDENCIES

=over

=back

=head1 BUGS AND LIMITATIONS

=head1 AUTHOR

Copyright (C) 2012 by Daniel Friesel E<lt>derf@finalrewind.orgE<gt>

=head1 LICENSE

  0. You just DO WHAT THE FUCK YOU WANT TO.
